module.exports = {

   unique_columns: [  
      ["CHECKSUM FILE", ""],
      ["CLASS NOMENCLATURE", ""],
      ["CLASS PRODUCTS", ""],
      ["CLASS PRODUCTS ON FORMULARY", ""],
      ["COINSURANCE", ""],
      ["COPAY RANGE", ""],
      ["CREATED AT (TIME STAMP)", ""],
      ["DRUG ID", ""],
      ["DRUG NAME", ""],
      ["FF PLAN ID", ""],
      ["FF PLAN NAME", ""],
      ["FF PLAN TYPE", ""],
      ["FF PRODUCT ID", ""],
      ["FF PROVIDER ID", ""],
      ["FF PROVIDER NAME", ""],
      ["FF PROVIDER-TYPE ID", ""],
      ["FF PROVIDER-TYPE NAME", ""],
      ["FILE NAME", ""],
      ["IMS PAYER ID", ""],
      ["IMS PAYER NAME", ""],
      ["IMS PAYER/PLAN ID", ""],
      ["IMS PLAN NAME", ""],
      ["MATERIAL RESTRICTION", ""],
      ["NNI ID", ""],
      ["NNI NAME", ""],
      ["OR", ""],
      ["PA", ""],
      ["PARENT ID", ""],
      ["PARENT NAME", ""],
      ["PBM_FUNCTION_ID", ""],
      ["PBM_FUNCTION_NAME", ""],
      ["PBM_ID", ""],
      ["PBM_NAME", ""],
      ["PLAN TYPE", ""],
      ["PLAN_ID", ""],
      ["PLAN_NAME", ""],
      ["PREFERRED BRAND TIER", ""],
      ["PROVIDER ID", ""],
      ["PROVIDER NAME", ""],
      ["QL", ""],
      ["REASON CODE", ""],
      ["RECORD COUNT", ""],
      ["RESTRICTION DETAIL", ""],
      ["ST", ""],
      ["STATE(S) OF OPERATION", ""],
      ["STATUS", ""],
      ["SUBCLASS NAME", ""],
      ["SUBCLASS NOMENCLATURE", ""],
      ["SUBCLASS PRODUCTS", ""],
      ["SUBCLASS PRODUCTS ON FORMULARY", ""],
      ["TIER", ""],
      ["WK PLAN ID", ""],
      ["WK PLAN NAME", ""],
      ["ZIP CODE", ""],
      ["ZIP CODE LIVES", ""]
   ],

   schema: {  
      "DATA/FF_IMS_HIERARCHY.TXT":[  
         "FF PLAN ID",
         "FF PLAN NAME",
         "FF PLAN TYPE",
         "IMS PAYER/PLAN ID",
         "IMS PLAN NAME",
         "IMS PAYER ID",
         "IMS PAYER NAME",
         "FF PROVIDER-TYPE ID",
         "FF PROVIDER-TYPE NAME",
         "FF PROVIDER ID",
         "FF PROVIDER NAME",
         "NNI ID",
         "NNI NAME"
      ],
      "DATA/FF_WK_HIERARCHY.TXT":[  
         "FF PLAN ID",
         "FF PLAN NAME",
         "FF PLAN TYPE",
         "WK PLAN ID",
         "WK PLAN NAME",
         "FF PROVIDER-TYPE ID",
         "FF PROVIDER-TYPE NAME",
         "FF PROVIDER ID",
         "FF PROVIDER NAME",
         "NNI ID",
         "NNI NAME"
      ],
      "DATA/FORMULARY_EXTRACT.TXT":[  
         "FF PLAN ID",
         "FF PLAN NAME",
         "PROVIDER ID",
         "PROVIDER NAME",
         "PARENT ID",
         "PARENT NAME",
         "PLAN TYPE",
         "STATE(S) OF OPERATION",
         "PREFERRED BRAND TIER",
         "DRUG ID",
         "DRUG NAME",
         "TIER",
         "COPAY RANGE",
         "COINSURANCE",
         "PA",
         "QL",
         "ST",
         "OR",
         "REASON CODE",
         "RESTRICTION DETAIL"
      ],
      "DATA/PBM_DATA.TXT":[  
         "PLAN_ID",
         "PLAN_NAME",
         "PBM_ID",
         "PBM_NAME",
         "PBM_FUNCTION_ID",
         "PBM_FUNCTION_NAME"
      ],
      "DATA/TIER_NOMENCLATURE.TXT":[  
         "FF PLAN ID",
         "FF PRODUCT ID",
         "STATUS",
         "MATERIAL RESTRICTION",
         "CLASS NOMENCLATURE",
         "CLASS PRODUCTS",
         "CLASS PRODUCTS ON FORMULARY",
         "SUBCLASS NAME",
         "SUBCLASS NOMENCLATURE",
         "SUBCLASS PRODUCTS",
         "SUBCLASS PRODUCTS ON FORMULARY",
         "PA",
         "QL",
         "ST",
         "OR",
         "REASON CODE",
         "RESTRICTION DETAIL",
         "COPAY RANGE"
      ],
      "DATA/ZIP_LEVEL_LIVES.TXT":[  
         "FF PLAN ID",
         "ZIP CODE",
         "ZIP CODE LIVES"
      ],
      "DATA/CONTROL.TXT":[  
         "FILE NAME",
         "RECORD COUNT",
         "CREATED AT (TIME STAMP)",
         "CHECKSUM FILE"
      ]
   }
   
};

